-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.item
(
    id serial NOT NULL,
    sku character varying(255),
    category_id integer DEFAULT 0,
    item_name character varying(255) NOT NULL,
    description text DEFAULT 'Component description goes here',
    img_path character varying(255),
    quantity real DEFAULT 0,
    unit character varying(56),
    price money DEFAULT 0,
    cost money DEFAULT 0,
    for_sale boolean DEFAULT true,
    slug character varying(255) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.component
(
    parent_id integer NOT NULL,
    child_id integer NOT NULL,
    child_qty real
);

CREATE TABLE IF NOT EXISTS public."user"
(
    id serial NOT NULL,
    email character varying(255) NOT NULL,
    pass_hash character varying(255) NOT NULL,
    username character varying(255) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.category
(
    id serial NOT NULL,
    category_name character varying(255) NOT NULL,
    description text DEFAULT 'Category description goes here',
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.item_details
(
    item_id integer NOT NULL,
    created_by integer NOT NULL,
    updated_by integer NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT unique_item_id UNIQUE (item_id)
);

CREATE TABLE IF NOT EXISTS public.category_detail
(
    category_id integer NOT NULL,
    created_by integer NOT NULL,
    updated_by integer NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT unique_category_id UNIQUE (category_id)
);

ALTER TABLE IF EXISTS public.item
    ADD CONSTRAINT category_id FOREIGN KEY (category_id)
    REFERENCES public.category (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.component
    ADD CONSTRAINT parent_id FOREIGN KEY (parent_id)
    REFERENCES public.item (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.component
    ADD CONSTRAINT child_id FOREIGN KEY (child_id)
    REFERENCES public.item (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.item_details
    ADD CONSTRAINT created_by FOREIGN KEY (created_by)
    REFERENCES public."user" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.item_details
    ADD CONSTRAINT updated_by FOREIGN KEY (updated_by)
    REFERENCES public."user" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.item_details
    ADD CONSTRAINT item_id FOREIGN KEY (item_id)
    REFERENCES public.item (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.category_detail
    ADD CONSTRAINT created_by FOREIGN KEY (created_by)
    REFERENCES public."user" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.category_detail
    ADD CONSTRAINT updated_by FOREIGN KEY (updated_by)
    REFERENCES public."user" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.category_detail
    ADD CONSTRAINT category_id FOREIGN KEY (category_id)
    REFERENCES public.category (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;