-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.category
(
    id integer NOT NULL DEFAULT nextval('category_id_seq'::regclass),
    category_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default" DEFAULT 'Category description goes here'::text,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    created_by integer NOT NULL,
    updated_by integer NOT NULL,
    CONSTRAINT category_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.component
(
    parent_id integer NOT NULL,
    child_id integer NOT NULL,
    child_qty real
);

CREATE TABLE IF NOT EXISTS public.item
(
    id integer NOT NULL DEFAULT nextval('item_id_seq'::regclass),
    sku character varying(255) COLLATE pg_catalog."default",
    category_id integer DEFAULT 0,
    item_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default" DEFAULT 'Component description goes here'::text,
    img_path character varying(255) COLLATE pg_catalog."default",
    quantity real DEFAULT 0,
    unit character varying(56) COLLATE pg_catalog."default" DEFAULT 'Individual'::character varying,
    price money DEFAULT 0,
    cost money DEFAULT 0,
    for_sale boolean DEFAULT true,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    created_by integer NOT NULL,
    updated_by integer NOT NULL,
    CONSTRAINT item_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.units_user
(
    id integer NOT NULL DEFAULT nextval('user_id_seq'::regclass),
    email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    pass_hash character varying(255) COLLATE pg_catalog."default" NOT NULL,
    username character varying(255) COLLATE pg_catalog."default" NOT NULL,
    signup timestamp with time zone NOT NULL DEFAULT now(),
    last_login timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT user_pkey PRIMARY KEY (id),
    CONSTRAINT email_u UNIQUE (email),
    CONSTRAINT username_u UNIQUE (username)
);

ALTER TABLE IF EXISTS public.category
    ADD CONSTRAINT created_by_fk FOREIGN KEY (created_by)
    REFERENCES public.units_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.category
    ADD CONSTRAINT updated_by_fk FOREIGN KEY (updated_by)
    REFERENCES public.units_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.component
    ADD CONSTRAINT child_id FOREIGN KEY (child_id)
    REFERENCES public.item (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.component
    ADD CONSTRAINT parent_id FOREIGN KEY (parent_id)
    REFERENCES public.item (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.item
    ADD CONSTRAINT category_id_fk FOREIGN KEY (category_id)
    REFERENCES public.category (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.item
    ADD CONSTRAINT created_by_fk FOREIGN KEY (created_by)
    REFERENCES public.units_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.item
    ADD CONSTRAINT updated_by_fk FOREIGN KEY (updated_by)
    REFERENCES public.units_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;